-- 7
SELECT 
	CARTON.CARTON_ID,
	(CARTON.LEN * CARTON.WIDTH * CARTON.HEIGHT) AS CARTON_VOL
FROM 
	CARTON
WHERE 
	(CARTON.LEN * CARTON.WIDTH * CARTON.HEIGHT) >= (
		SELECT 
			SUM(PRODUCT.LEN * PRODUCT.HEIGHT * PRODUCT.WIDTH * ORDER_ITEMS.PRODUCT_QUANTITY) AS PRODUCT_VOL
		FROM 
			ORDER_ITEMS
		INNER JOIN PRODUCT ON PRODUCT.PRODUCT_ID = ORDER_ITEMS.PRODUCT_ID
		WHERE ORDER_ITEMS.ORDER_ID = 10006
	)
ORDER BY CARTON_VOL LIMIT 1; 


